version: "3"

services:                   # precise les differentes images a utiliser
 nginx:
  image: nginx:mytag
  build:
    context: requirements/nginx
    dockerfile: Dockerfile
  env_file: .env
  volumes:
   - wp-volume:/var/www/
  networks:
   - inception
  container_name: nginx
  ports:
   - "443:443"
  restart: always
  depends_on:
   - wordpress


 mariadb:
  image: mariadb:mytag
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
   args:
     DB_NAME: ${DB_NAME}
     DB_USER: ${DB_USER}
     DB_PASS: ${DB_PASS}
     DB_ROOT: ${DB_ROOT}
  container_name: mariadb
  networks:
   - inception
  env_file: .env
  restart: always
  volumes:
   - db-volume:/var/lib/mysql


 wordpress:
  image: wordpress:mytag
  build:
    context: requirements/wordpress
    dockerfile: Dockerfile
    args:
     DB_NAME: ${DB_NAME}
     DB_USER: ${DB_USER}
     DB_PASS: ${DB_PASS}
     DB_ROOT: ${DB_ROOT}
  env_file: .env
  networks:
   - inception
  container_name: wordpress
  depends_on:
   - mariadb
  restart: always
  volumes:
   - wp-volume:/var/www/

volumes:
  wp-volume:
   driver_opts:
    o: bind
    type: none
    device: /home/${USER}/data/wordpress
  db-volume:
   driver_opts:
    o: bind
    type: none
    device: /home/${USER}/data/mariadb
   
networks:
 inception:
  driver: bridge 
